apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
        - name: client
          image: medhat521/multi-client
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
