name: first-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: echo "Hello World" && echo "Muhammad Medhat"
      - name: Farwell
        run: echo "Goodbye" && echo "Muhammad Medhat"
